# name: Integration workflow

# on:
#   push:
#     branches: ['main']
#   pull_request:
#     branches: ['main']
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [20]

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install dependencies
#         run: npm install

#       - name: Build the Vite project
#         run: npm run build

#       # - name: Check for linting issues
#       #   run: npm run lint

#       # - name: Build The project
#       #   run: npm run build
#       - name: Upload production artifacts
#         uses: actions/upload-artifact@v3
#         with:
#           name: production-files
#           path: dist/

#   deploy-Project:
#     name: Deploy Project
#     runs-on: ubuntu-latest
#     needs: ['build']
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Set up SSH connection
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: ${{ secrets.USER_NAME }}
#           key: ${{ secrets.SEVER_SSH_KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             set -e
#             echo "Changing Directory to /www/wwwroot/CLIENTS/mnnclient"
#             if ! cd /www/wwwroot/CLIENTS/mnnclient; then 
#                echo "Failed to change directory"
#                exit 1;
#             fi
#             echo "Pulling Latest Code from origin/main"
#             if ! git pull origin main; then 
#                echo "Failed to pull latest codes"
#                exit 1
#             fi
#             echo "Install Dependencies"
#             if ! npm install; then 
#                echo "Failed to Install dependencies"
#                exit 1;
#             fi
#             # echo "Building Production"
#             # if ! npm run build; then
#             #    echo "Failed to Build Project"
#             #    exit 1;
#             # fi 
#             echo "Deployment Successful"
